// Audited action kinds (audit_log.action)
package com.docshelf.audit.entity;

public enum AuditAction { UPLOAD_DOCUMENT, DELETE_DOCUMENT, DOWNLOAD_ORIGINAL, REVEAL_FIELD, SHARE_DOCUMENT, FIELD_EDIT, PENDING_ACTION_CREATED, PENDING_ACTION_CONFIRMED, PENDING_ACTION_CANCELLED, LLM_CALL, VISION_CALL, REMINDER_SENT, REMINDER_CREATED }
